//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sundew.Injection.Generator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sundew.Injection.Generator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find exact match while resolving a required parameter..
        /// </summary>
        internal static string ResolveRequiredParameterErrorDescription {
            get {
                return ResourceManager.GetString("ResolveRequiredParameterErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cound not resolve exact match of parameter &apos;{0}&apos; &apos;{1}&apos; in type: &apos;{3}&apos;. Possible candicates are: &apos;{4}&apos;.
        /// </summary>
        internal static string ResolveRequiredParameterErrorMessageFormat {
            get {
                return ResourceManager.GetString("ResolveRequiredParameterErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve required parameter by an exact match..
        /// </summary>
        internal static string ResolveRequiredParameterErrorTitle {
            get {
                return ResourceManager.GetString("ResolveRequiredParameterErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type could not be resolved while generating a factory. Verify that it has a binding or that the type has an accessible constructor..
        /// </summary>
        internal static string ResolveTypeErrorDescription {
            get {
                return ResourceManager.GetString("ResolveTypeErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the type: &apos;{0}&apos;, while constructing &apos;{1}&apos;-.
        /// </summary>
        internal static string ResolveTypeErrorMessageFormat {
            get {
                return ResourceManager.GetString("ResolveTypeErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve type while generating factory..
        /// </summary>
        internal static string ResolveTypeErrorTitle {
            get {
                return ResourceManager.GetString("ResolveTypeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scope error indicate that the scope of a binding is invalid. E.g. a SingleInstancePerFactory cannot inject a SingleInstancePerRequest..
        /// </summary>
        internal static string ScopeErrorDescription {
            get {
                return ResourceManager.GetString("ScopeErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope &apos;{0}&apos; for the type &apos;{1}&apos; is invalid because the injection target &apos;{2}&apos; is registered as: &apos;{3}&apos;.
        /// </summary>
        internal static string ScopeErrorMessageFormat {
            get {
                return ResourceManager.GetString("ScopeErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scope error occured while generating factory..
        /// </summary>
        internal static string ScopeErrorTitle {
            get {
                return ResourceManager.GetString("ScopeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occured while running Sundew.Injection generator.
        /// </summary>
        internal static string UnknownErrorDescription {
            get {
                return ResourceManager.GetString("UnknownErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured with the message: &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownErrorMessageFormat {
            get {
                return ResourceManager.GetString("UnknownErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occured.
        /// </summary>
        internal static string UnknownErrorTitle {
            get {
                return ResourceManager.GetString("UnknownErrorTitle", resourceCulture);
            }
        }
    }
}
